In [1]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine,URL

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
conn = psycopg2.connect(
  host='localhost',
  port=5432,
  dbname='postgres',
  user='postgres',
  password='postgres'
)
conn.set_session(autocommit=True)
cursor = conn.cursor()

In [4]:
engine = create_engine(
  URL.create(
    drivername='postgresql+psycopg2',
    host='localhost',
    port=5432,
    database='postgres',
    username='postgres',
    password='postgres'
  )
)

In [6]:
# read m1_total
cursor.execute(
  'select * from m4_total'
)
y_df = pd.DataFrame(
  cursor.fetchall(),
  columns=[col.name for col in cursor.description]
)

In [7]:
y_df['deal_amount'] = y_df.deal_amount.astype('int64')

In [8]:
y_df

,deal_amount,contract_year,contract_month,contract_day,floor,plottage,land_use,build_year,building_age,building_type,building_detail_type,building_use,building_area,sig_cd,emd_cd,pnu,longitude,latitude,geom,geom_3857,plat_area,arch_area,tot_area,elev_cnt,parklot_cnt,base_year_x,sig_store_cnt,sig_sales_amt,sig_sales_cnt,sig_delivery_amt,sig_delivery_cnt,sig_sales_restaurant_amt,sig_sales_service_amt,sig_sales_retail_amt,sig_sales_etc_amt,sig_sales_wk_amt,sig_sales_we_amt,sig_sales_morning_amt,sig_sales_afternoon_amt,sig_sales_evening_amt,sig_sales_night_amt,sig_sales_male_amt,sig_sales_female_amt,sig_sales_age20_amt,sig_sales_age30_amt,sig_sales_age40_amt,sig_sales_age50_amt,sig_sales_age60_amt,base_year_y,emd_store_cnt,emd_sales_amt,emd_sales_cnt,emd_delivery_amt,emd_delivery_cnt,emd_sales_restaurant_amt,emd_sales_service_amt,emd_sales_retail_amt,emd_sales_etc_amt,emd_sales_wk_amt,emd_sales_we_amt,emd_sales_morning_amt,emd_sales_afternoon_amt,emd_sales_evening_amt,emd_sales_night_amt,emd_sales_male_amt,emd_sales_female_amt,emd_sales_age20_amt,emd_sales_age30_amt,emd_sales_age40_amt,emd_sales_age50_amt,emd_sales_age60_amt,plp_amt,subway_dist,subway_500_cnt,subway_1000_cnt,base_year,walk_tot_cnt,walk_male_cnt,walk_female_cnt,walk_age_u20_cnt,walk_age_20_cnt,walk_age_30_cnt,walk_age_40_cnt,walk_age_50_cnt,walk_age_o50_cnt,walk_morning_cnt,walk_afternoon_cnt,walk_evening_cnt,walk_time_night_cnt,live_pop,work_pop,school_type_1_cnt,school_type_2_cnt,school_type_3_cnt,school_type_4_cnt,school_type_5_cnt,school_type_6_cnt
0,1090000000,2021,4,20,4,None,일반상업,2009,12.0,집합,공장/창고,공장,120.53,11140,11140159,1114015900100420000,126.99251891479467,37.563820788135864,0101000020E610000017ED0D6E85BF5F409BEC92472BC8...,0101000020110F0000DFE848D1B4F66A418025D58F193C...,1922.8,1147.6900,17947.7800,3,47,2021,158739,1.368472e+14,2.091166e+09,0.000000e+00,0.0,2.265498e+12,3.983378e+13,1.151426e+13,8.323370e+13,1.209723e+14,1.587490e+13,2.739852e+13,8.048548e+13,1.759848e+13,1.136445e+13,6.378077e+13,6.298627e+13,1.204007e+13,2.946716e+13,4.029361e+13,2.901990e+13,1.594629e+13,2021,2000,3.993359e+10,2606274.0,0.0,0.0,2.317726e+10,3.615012e+09,8.529372e+09,4.611944e+09,3.425042e+10,5.683175e+09,3.873355e+09,2.266345e+10,1.168731e+10,1.709692e+09,2.270539e+10,1.506564e+10,8.086689e+09,8.880954e+09,8.520427e+09,8.421692e+09,3.861269e+09,18460000.0,215.0,2.0,5.0,2021,24336223.038389547981,10931949.65,7928059.38,454099.73,3545758.43,3428906.11,3460250.34,3859391.35,411115792.39,3016687.41,8189311.92,5278321.21,2375688.58,4911.0,255385.0,1.0,1.0,4.0,1.0,NaN,NaN
1,400000000,2021,12,13,1,None,중심상업,2008,13.0,집합,상가/사무실,제2종근린생활,10.53,11140,11140105,1114010500101990040,126.98386806204908,37.56470999106414,0101000020E61000001A85BFB1F7BE5F4027ACBF6A48C8...,0101000020110F0000C11703713CF66A415DBAE8C7383C...,2776.1,1665.2000,19135.8440,3,75,2021,158739,1.368472e+14,2.091166e+09,0.000000e+00,0.0,2.265498e+12,3.983378e+13,1.151426e+13,8.323370e+13,1.209723e+14,1.587490e+13,2.739852e+13,8.048548e+13,1.759848e+13,1.136445e+13,6.378077e+13,6.298627e+13,1.204007e+13,2.946716e+13,4.029361e+13,2.901990e+13,1.594629e+13,2021,3629,3.807772e+13,333459294.0,0.0,0.0,6.365721e+10,3.722099e+12,3.803102e+11,3.391165e+13,3.740046e+13,6.772597e+11,1.120783e+13,2.214534e+13,3.957188e+12,7.669540e+11,1.695023e+13,1.819665e+13,1.477833e+12,6.415006e+12,1.216795e+13,9.725638e+12,5.360453e+12,29310000.0,163.0,1.0,6.0,2021,27492910.778659108885,11466711.51,10367508.10,694418.51,4455390.22,5375321.41,4498790.07,3628520.17,318177970.52,3343409.79,10621578.85,5965905.52,1903325.94,4883.0,422600.0,26.0,NaN,1.0,NaN,NaN,NaN
2,340000000,2022,4,7,2,None,일반상업,2021,1.0,집합,상가/사무실,제2종근린생활,46.55,11140,11140132,1114013200103340000,126.99751945474308,37.56291931102084,0101000020E6100000B3CFD65BD7BF5F40898F6FBD0DC8...,0101000020110F0000B7A55366FAF66A4119C188E9F93B...,1383.9,986.8200,15894.4900,3,47,2022,164664,1.510287e+14,2.364908e+09,4.648226e+09,231234.0,2.962805e+12,4.413300e+13,1.648516e+13,8.744771e+13,1.321750e+14,1.885367e+13,3.682426e+13,8.005443e+13,1.982770e+13,1.432253e+13,6.989898e+13,7.146669e+13,1.223453e+13,3.171137e+13,4.480255e+13,3.366935e+13,1.894786e+13,2022,2136,3.213967e+10,1368771.0,52567288.0,2680.0,2.049365e+10,2.570445e+09,7.254175e+09,1.821409e+09,2.701694e+10,5.122751e+09,2.368322e+09,1.495823e+10,1.059043e+10,4.222777e+09,2.035465e+10,9.008101e+09,5.788073e+09,5.255243e+09,6.375060e+09,7.192543e+09,4.751835e+09,14860000.0,291.0,2.0,5.0,2022,18803981.961860471049,11005036.26,7798945.54,792399.93,3662302.74,2686880.59,2855261.44,3853206.02,495367005.92,3004039.05,7765935.96,4822728.55,3211278.82,10167.0,174367.0,2.0,1.0,1.0,1.0,NaN,1.0
3,688500000,2022,4,7,1,None,일반상업,2021,1.0,집합,상가/사무실,숙박,43.55,11140,11140132,1114013200103340000,126.99751945474308,37.56291931102084,0101000020E6100000B3CFD65BD7BF5F40898F6FBD0DC8...,0101000020110F0000B7A55366FAF66A4119C188E9F93B...,1383.9,986.8200,15894.4900,3,47,2022,164664,1.510287e+14,2.364908e+09,4.648226e+09,231234.0,2.962805e+12,4.413300e+13,1.648516e+13,8.744771e+13,1.321750e+14,1.885367e+13,3.682426e+13,8.005443e+13,1.982770e+13,1.432253e+13,6.989898e+13,7.146669e+13,1.223453e+13,3.171137e+13,4.480255e+13,3.366935e+13,1.894786e+13,2022,2136,3.213967e+10,1368771.0,52567288.0,2680.0,2.049365e+10,2.570445e+09,7.254175e+09,1.821409e+09,2.701694e+10,5.122751e+09,2.368322e+09,1.495823e+10,1.059043e+10,4.222777e+09,2.035465e+10,9.008101e+09,5.788073e+09,5.255243e+09,6.375060e+09,7.192543e+09,4.751835e+09,14860000.0,291.0,2.0,5.0,2022,18803981.961860471049,11005036.26,7798945.54,792399.93,3662302.74,2686880.59,2855261.44,3853206.02,495367005.92,3004039.05,7765935.96,4822728.55,3211278.82,10167.0,174367.0,2.0,1.0,1.0,1.0,NaN,1.0
4,235000000,2022,3,5,13,None,일반상업,2005,17.0,집합,상가/사무실,숙박,43.34,11140,11140133,1114013300100220005,127.00074224628915,37.56385078909955,0101000020E610000066E234290CC05F40D0803D432CC8...,0101000020110F0000AF95A13E27F76A41A51E7A9D1A3C...,1216.0,729.4700,11622.4710,2,48,2022,164664,1.510287e+14,2.364908e+09,4.648226e+09,231234.0,2.962805e+12,4.413300e+13,1.648516e+13,8.744771e+13,1.321750e+14,1.885367e+13,3.682426e+13,8.005443e+13,1.982770e+13,1.432253e+13,6.989898e+13,7.146669e+13,1.223453e+13,3.171137e+13,4.480255e+13,3.366935e+13,1.894786e+13,2022,1000,2.478990e+10,967254.0,60929244.0,3470.0,1.227282e+10,7.505635e+09,3.952624e+09,1.058821e+09,2.002654e+10,4.763360e+09,1.899996e+09,1.429190e+10,6.165419e+09,2.432552e+09,1.454618e+10,9.361554e+09,6.830649e+09,5.117747e+09,4.213916e+09,4.919785e+09,2.825637e+09,10720000.0,347.0,2.0,6.0,2022,16972138.135455565669,9533296.89,7438841.25,779009.01,3088476.01,2908660.82,2587554.24,3177488.61,442936024.61,2873231.99,6662418.51,3959229.24,3477258.12,13119.0,155339.0,4.0,1.0,1.0,1.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11663,375000000,2021,1,11,23,None,일반상업,1999,22.0,집합,상가/사무실,업무,27.93,11680,11680118,1168011800104670006,127.05107760555774,37.48812016230573,0101000020E61000006C5B01DB44C35F4087CFB2B87ABE...,0101000020110F000036F270A8E3F96A41E4C3AF26B931...,NaN,NaN,NaN,None,None,2021,334095,1.387321e+14,1.307105e+09,0.000000e+00,0.0,4.012875e+12,3.691905e+13,1.115129e+13,8.664885e+13,1.254156e+14,1.331643e+13,2.211841e+13,8.286332e+13,1.434368e+13,1.940468e+13,8.512833e+13,5.259453e+13,8.558684e+12,2.327611e+13,4.376995e+13,3.754294e+13,2.457518e+13,2021,16696,2.370684e+12,131914759.0,0.0,0.0,2.043650e+11,5.988019e+11,1.440049e+12,1.274681e+11,1.683125e+12,6.875596e+11,2.745040e+11,1.493761e+12,5.616956e+11,4.073121e+10,1.189783e+12,1.173975e+12,2.434859e+11,5.200278e+11,6.843184e+11,5.427270e+11,3.731984e+11,42260000.0,513.0,NaN,3.0,2021,18639278.6451779442978,5991168.50,7961611.97,3233847.17,1366740.56,1455813.44,2382783.37,2399230.21,311434120.44,2145875.26,4290488.43,3554464.61,3961952.00,30515.0,36199.0,NaN,1.0,3.0,5.0,3.0,NaN
11664,520000000,2020,6,29,27,None,일반상업,1999,21.0,집합,상가/사무실,업무,45.78,11680,11680118,1168011800104670006,127.05107760555774,37.48812016230573,0101000020E61000006C5B01DB44C35F4087CFB2B87ABE...,0101000020110F000036F270A8E3F96A41E4C3AF26B931...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42260000.0,513.0,NaN,3.0,2020,18639278.6451779442978,5991168.50,7961611.97,3233847.17,1366740.56,1455813.44,2382783.37,2399230.21,311434120.44,2145875.26,4290488.43,3554464.61,3961952.00,30515.0,36199.0,NaN,1.0,3.0,5.0,3.0,NaN
11665,400000000,2020,6,4,1,None,일반상업,1998,22.0,집합,상가/사무실,제2종근린생활,15.22,11680,11680118,1168011800104670024,127.05188285074247,37.48651648723156,0101000020E610000061CA720C52C35F40EBCF182C46BE...,0101000020110F00003699E7DCEEF96A41609ADBE78031...,10690.5,5956.2800,100496.7300,16,902,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38150000.0,575.0,NaN,3.0,2020,20456971.5191674742513,6514453.85,8573217.11,3478803.58,1386964.77,1542522.72,2485649.07,2557334.45,363637215.31,2296132.82,4512561.13,3784374.92,4494602.36,24985.0,36299.0,NaN,1.0,3.0,4.0,3.0,NaN
11666,700000000,2021,8,21,1,None,제3종일반주거,2006,15.0,집합,상가/사무실,제2종근린생활,61.56,11680,11680118,1168011800105270003,127.05265224220004,37.49534049353043,0101000020E6100000DB9382A75EC35F40810C3A5167BF...,0101000020110F00000930A691F9F96A4121084E67B632...,4359.3,2177.5257,19722.1145,3,156,2021,334095,1.387321e+14,1.307105e+09,0.000000e+00,0.0,4.012875e+12,3.691905e+13,1.115129e+13,8.664885e+13,1.254156e+14,1.331643e+13,2.211841e+13,8.286332e+13,1.434368e+13,1.940468e+13,8.512833e+13,5.259453e+13,8.558684e+12,2.327611e+13,4.376995e+13,3.754294e+13,2.457518e+13,2021,16696,2.370684e+12,131914759.0,0.0,0.0,2.043650e+11,5.988019e+11,1.440049e+12,1.274681e+11,1.683125e+12,6.875596e+11,2.745040e+11,1.493761e+12,5.616956e+11,4.073121e+10,1.189783e+12,1.173975e+12,2.434859e+11,5.200278e+11,6.843184e+11,5.427270e+11,3.731984e+11,19440000.0,98.0,1.0,2.0,2021,30412355.139933593646,10061506.61,13227230.95,8909383.73,2208255.99,1406094.74,4515168.97,3180238.33,306959572.86,2876435.77,6879653.39,6892072.58,6640575.56,37708.0,31656.0,7.0,1.0,3.0,5.0,4.0,NaN
11667,1529490000,2021,6,29,3,None,제3종일반주거,1980,41.0,집합,상가/사무실,제1종근린생활,149.34,11680,11680118,1168011800109020002,127.03815409534478,37.48642652410782,0101000020E6100000B7EDDF1D71C25F409B796E3943BE...,0101000020110F0000ECBA01D42FF96A41D2BB1EC07D31...,0.0,0.0000,1830.5300,0,0,2021,334095,1.387321e+14,1.307105e+09,0.000000e+00,0.0,4.012875e+12,3.691905e+13,1.115129e+13,8.664885e+13,1.254156e+14,1.331643e+13,2.211841e+13,8.286332e+13,1.434368e+13,1.940468e+13,8.512833e+13,5.259453e+13,8.558684e+12,2.327611e+13,4.376995e+13,3.754294e+13,2.457518e+13,2021,16696,2.370684e+12,131914759.0,0.0,0.0,2.043650e+11,5.988019e+11,1.440049e+12,1.274681e+11,1.683125e+12,6.875596e+11,2.745040e+11,1.493761e+12,5.616956e+11,4.073121e+10,1.189783e+12,1.173975e+12,2.434859e+11,5.200278e+11,6.843184e+11,5.427270e+11,3.731984e+11,14140000.0,448.0,1.0,2.0,2021,19449389.9129951434109,7038205.05,7970216.14,2812801.90,1987560.21,2302466.52,2827956.46,2338357.42,273927930.37,2208871.33,5076276.54,4254974.64,3468298.62,12964.0,95856.0,3.0,1.0,1.0,1.0,2.0,NaN

In [9]:
y_df.describe()

,deal_amount,plat_area,arch_area,tot_area,sig_sales_amt,sig_sales_cnt,sig_delivery_amt,sig_delivery_cnt,sig_sales_restaurant_amt,sig_sales_service_amt,sig_sales_retail_amt,sig_sales_etc_amt,sig_sales_wk_amt,sig_sales_we_amt,sig_sales_morning_amt,sig_sales_afternoon_amt,sig_sales_evening_amt,sig_sales_night_amt,sig_sales_male_amt,sig_sales_female_amt,sig_sales_age20_amt,sig_sales_age30_amt,sig_sales_age40_amt,sig_sales_age50_amt,sig_sales_age60_amt,emd_sales_amt,emd_sales_cnt,emd_delivery_amt,emd_delivery_cnt,emd_sales_restaurant_amt,emd_sales_service_amt,emd_sales_retail_amt,emd_sales_etc_amt,emd_sales_wk_amt,emd_sales_we_amt,emd_sales_morning_amt,emd_sales_afternoon_amt,emd_sales_evening_amt,emd_sales_night_amt,emd_sales_male_amt,emd_sales_female_amt,emd_sales_age20_amt,emd_sales_age30_amt,emd_sales_age40_amt,emd_sales_age50_amt,emd_sales_age60_amt,plp_amt,subway_dist,subway_500_cnt,subway_1000_cnt,school_type_1_cnt,school_type_2_cnt,school_type_3_cnt,school_type_4_cnt,school_type_5_cnt,school_type_6_cnt
count,1.166800e+04,1.159300e+04,11593.000000,1.159300e+04,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,7.963000e+03,1.166500e+04,11668.000000,6922.000000,10733.000000,11319.000000,6938.000000,11274.000000,9752.000000,7366.000000,2150.000000
mean,4.265492e+08,1.215797e+04,3039.255256,3.827616e+04,2.806418e+13,4.490674e+08,9.922561e+09,4.703369e+05,1.440020e+12,9.869507e+12,5.337324e+12,1.141733e+13,2.340206e+13,4.662115e+12,4.991257e+12,1.562272e+13,4.345246e+12,3.104901e+12,1.511867e+13,1.229575e+13,2.485572e+12,5.728490e+12,8.138343e+12,6.751609e+12,4.310402e+12,6.098423e+12,7.779576e+07,1.659651e+09,7.882071e+04,2.364521e+11,1.832016e+12,1.390983e+12,2.638972e+12,5.058655e+12,1.039768e+12,9.934012e+11,3.464285e+12,9.030863e+11,7.376382e+11,3.451383e+12,2.526941e+12,5.020825e+11,1.236948e+12,1.794637e+12,1.507778e+12,9.368785e+11,1.009718e+07,497.503771,1.175672,2.125221,6.759961,1.536754,2.802288,1.944217,1.978957,1.320000
std,3.469614e+08,1.177859e+05,11910.548110,9.383979e+04,4.315666e+13,5.103003e+08,2.099798e+10,9.799672e+05,1.175887e+12,1.304407e+13,5.633314e+12,2.728313e+13,3.875816e+13,4.854047e+12,8.253756e+12,2.464886e+13,5.067944e+12,5.852727e+12,2.499572e+13,1.753909e+13,3.035722e+12,7.817782e+12,1.333123e+13,1.136568e+13,7.233590e+12,1.891210e+13,1.752643e+08,4.833887e+09,2.245807e+05,2.451662e+11,5.651336e+12,2.925932e+12,1.310775e+13,1.710970e+13,2.181247e+12,3.131922e+12,1.079423e+13,2.104248e+12,3.177859e+12,1.175783e+13,7.144747e+12,1.238676e+12,3.255312e+12,6.058771e+12,5.260069e+12,3.296589e+12,8.451957e+06,395.188431,0.396193,1.059175,5.099668,0.789064,1.211667,0.975216,1.168827,0.569032
min,3.000000e+06,0.000000e+00,0.000000,0.000000e+00,1.656092e+12,6.907014e+07,0.000000e+00,0.000000e+00,3.524939e+11,3.495775e+11,8.142789e+11,1.094578e+10,1.178830e+12,4.772614e+11,2.013182e+11,9.166866e+11,4.448912e+11,7.402196e+10,8.619494e+11,7.432593e+11,1.430164e+11,2.751031e+11,3.689845e+11,3.833084e+11,3.379208e+11,1.681183e+09,1.316980e+05,0.000000e+00,0.000000e+00,1.520331e+08,2.676613e+08,7.314371e+08,0.000000e+00,1.248929e+09,4.322541e+08,2.812388e+08,7.427527e+08,4.514582e+08,6.140546e+07,9.690198e+08,6.590708e+08,2.113641e+08,5.119333e+08,3.946209e+08,3.237218e+08,1.864506e+08,8.595000e+05,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.840000e+08,3.524000e+02,353.620000,3.141080e+03,3.420022e+12,1.137011e+08,0.000000e+00,0.000000e+00,6.314167e+11,6.956755e+11,1.680583e+12,7.437162e+10,2.570991e+12,8.173969e+11,4.035532e+11,1.968269e+12,7.282140e+11,1.474549e+11,1.675695e+12,1.640166e+12,3.302948e+11,6.650521e+11,7.716668e+11,7.721407e+11,6.246364e+11,3.538874e+11,1.131982e+07,0.000000e+00,0.000000e+00,5.500156e+10,6.830677e+10,1.356353e+11,2.871444e+09,2.558743e+11,8.188539e+10,3.654835e+10,2.027551e+11,7.850548e+10,1.279311e+10,1.708434e+11,1.574470e+11,2.948276e+10,5.718776e+10,8.189925e+10,7.546372e+10,5.918404e+10,4.820000e+06,221.000000,1.000000,1.000000,3.000000,1.000000,2.000000,1.000000,1.000000,1.000000
50%,3.200000e+08,1.829400e+03,1275.173000,1.934133e+04,1.346837e+13,2.677478e+08,0.000000e+00,0.000000e+00,1.060975e+12,2.421343e+12,2.508912e+12,6.033764e+11,1.053732e+13,2.023025e+12,2.130835e+12,7.260552e+12,2.031295e+12,5.271108e+11,6.801648e+12,6.205790e+12,1.172981e+12,2.895713e+12,3.304298e+12,3.182757e+12,2.170796e+12,8.636457e+11,2.801849e+07,0.000000e+00,0.000000e+00,1.753293e+11,1.638282e+11,3.978796e+11,2.155070e+10,6.619199e+11,2.358230e+11,1.142651e+11,5.084912e+11,2.085127e+11,3.032797e+10,4.527557e+11,4.039304e+11,1.054797e+11,1.688004e+11,2.000078e+11,2.023019e+11,1.400698e+11,7.246000e+06,410.000000,1.000000,2.000000,6.000000,1.000000,3.000000,2.000000,2.000000,1.000000
75%,5.700000e+08,4.245100e+03,2729.590000,4.608371e+04,2.650741e+13,6.751383e+08,1.043973e+10,5.130830e+05,1.710194e+12,1.606342e+13,9.793654e+12,2.983120e+12,1.883139e+13,7.331353e+12,4.152005e+12,1.341720e+13,6.542244e+12,3.345476e+12,1.292758e+13,1.446435e+13,3.814376e+12,7.194879e+12,7.901585e+12,5.238866e+12,3.048894e+12,2.098696e+12,5.148241e+07,1.272581e+09,6.363200e+04,3.289512e+11,4.063204e+11,8.326716e+11,6.979033e+10,1.476721e+12,4.545022e+11,3.928321e+11,1.187506e+12,3.987411e+11,9.626433e+10,9.841749e+11,1.060987e+12,2.125263e+11,4.126824e+11,5.022585e+11,4.414312e+11,3.127787e+11,1.154000e+07,665.000000,1.000000,3.000000,9.000000,2.000000,3.000000,3.000000,3.000000,2.000000
max,2.230000e+09,4.017812e+06,235675.798000,5.205721e+06,1.688640e+14,2.442850e+09,1.468697e+11,6.728324e+06,5.829375e+12,4.799102e+13,2.761902e+13,1.041934e+14,1.511844e+14,2.003087e+13,4.001834e+13,9.410750e+13,2.416521e+13,2.534125e+13,1.032777e+14,7.643037e+13,1.223453e+13,3.310116e+13,5.202771e+13,4.929658e+13,3.127963e+13,1.347465e+14,9.702503e+08,5.424389e+10,2.650097e+06,1.478597e+12,3.315531e+13,1.981895e+13,9.670925e+13,1.233593e+14,1.138723e+13,2.210549e+13,7.556442e+13,1.346430e+13,2.361247e+13,8.572628e+13,4.886053e+13,6.503043e+12,1.931724e+13,4.341258e+13,4.129304e+13,2.461852e+13,7.816000e+07,3940.000000,4.000000,7.000000,109.000000,6.000000,9.000000,6.000000,9.000000,5.000000

In [10]:
y_df['by_arch_area_amount'] = y_df.deal_amount / y_df.arch_area

In [11]:
deal_df_clean = y_df[0:0]

for sig in y_df['sig_cd'].unique():
  tmp_df = y_df[y_df['sig_cd'] == sig]
  # IQR 계산
  Q1 = tmp_df['by_arch_area_amount'].quantile(0.25)
  Q3 = tmp_df['by_arch_area_amount'].quantile(0.75)
  IQR = Q3 - Q1

  # # 이상치 제거
  deal_df_clean = pd.concat([
    deal_df_clean,
    tmp_df[~((tmp_df['by_arch_area_amount'] < (Q1 - 1.5 * IQR)) | (tmp_df['by_arch_area_amount'] > (Q3 + 1.5 * IQR)))]
  ])

In [12]:
deal_df_clean['by_arch_area_amount'].describe()

count    1.064400e+04
mean     5.470079e+05
std      8.354177e+05
min      8.632060e+01
25%      1.075529e+05
50%      2.514069e+05
75%      6.633397e+05
max      9.674582e+06
Name: by_arch_area_amount, dtype: float64

In [13]:
y_final_df = deal_df_clean[deal_df_clean['subway_dist'] <= 1000]

In [15]:
y_final_df.to_sql(
  'm4_total_v2',
  engine,
  index=False,
  if_exists='replace'
)

248

In [16]:
y_final_df.to_csv(
  'm4_data_06.29.csv',
  sep=',',
  index=False
)